### PR TITLE
added a bunch of tests to be carried out manually before release fix #627

### LINKED ISSUE #627: Test plan
Step by step guide for testing.

### PR DESCRIPTION
**Pull request by saberraz**

### CODE REVIEW

**Comment by saberraz** [comment]
Please also add some public projects for running tests.

**Comment by PeterPetrik** [comment]
This looks great. Would it be possible to add instructions to tests specifically how can I replicate it without being creative? like "download exactly this and this project from mergin, add this point on this layers and so on"...

**Comment by saberraz** [comment]
@PeterPetrik there are couple of projects missing (public and private vector tiles), but the rest should be there.

**Comment by PeterPetrik** [comment]
@saberraz can you move test to folder https://github.com/lutraconsulting/input/tree/master/docs/developers and add the link to the index.md in the same place? thanks

**Pull request merged**
