### PR TITLE
clear render cache and refresh canvas after sync (fix #2007) + QgsQuick update

### LINKED ISSUE #2007: Map canvas is not rerendered after sync
With (or without) autosync, map canvas is not rerendered after project synchronization.
This means, when projects was updated with new features from another device, current devices will show new features only when you move with the map even after successful synchronization.

Expectation is, that re-rendering of map canvas is called after some changes was synchronized, so user will be able to see features immediately without need or moving the map.

### PR DESCRIPTION
**Pull request by alexbruy**
Without this user needs to pan/zoom canvas to see new/deleted features after sync.

Fixes #2007.

### CODE REVIEW

**Comment by alexbruy** [comment]
@tomasMizera if you are happy with this approach, I will open PR also in QGIS repo.

**Comment by alexbruy** [comment]
Pull-request to QGIS with new method for QgsQuick canvas https://github.com/qgis/QGIS/pull/48176

**Review by tomasMizera — APPROVED** [review]
👍🏻

**Comment by tomasMizera** [comment]
Approved, but please:
 - create another PR to QGIS with the `qml` changes
 - change commit hash in the qgsquick CI check (feel free to ping me with that)

**Comment by alexbruy** [comment]
@tomasMizera seems there are other upstream changes in QgsQuick which are not in the Input. Should I update the whole lib as part of this PR?

**Comment by tomasMizera** [comment]
@alexbruy there is a script in the `scripts` folder to update qgsquick locally, can you run that and see what are the incoming changes from QGIS?

**Review by tomasMizera — APPROVED** [review]
Looks good. 👍🏻  to merge

**Pull request merged**
