### PR TITLE
add some explanatory text to help out users understand what mergin is

### PR DESCRIPTION
**Pull request by PeterPetrik**
Screen Shot 2021-01-27 at 14 04 26

maybe @mostlyAtNight can advise on the correct text to display?

### CODE REVIEW

**Comment by mostlyAtNight** [comment]
Hi @PeterPetrik - I would use this:

Main text -> [Mergin Maps](link-to-mergin) provides cloud-based sync between your mobile and desktop. Also use it to share your projects with others and work collaboratively.

Sign up -> Sign up for free

**Comment by PeterPetrik** [comment]
Screen Shot 2021-01-27 at 14 47 04

**Comment by PeterPetrik** [comment]
1. tweak the spacing between logo and text
2. check when user starts typing

**Comment by PeterPetrik** [comment]
@wonder-sk 

now the text hides when the keyboard is up

Screen Shot 2021-01-28 at 11 03 36
Screen Shot 2021-01-28 at 11 03 45

**Comment by PeterPetrik** [comment]
unrelated test failures

**Pull request merged**
