### PR TITLE
Win build

### PR DESCRIPTION
**Pull request by PeterPetrik**

### CODE REVIEW

**Comment by PeterPetrik** [comment]
fix #498

**Comment by PeterPetrik** [comment]
@saberraz the installer https://www.dropbox.com/s/i83qsbio94rlfv2/inputapp-win-x86_64.exe?dl=0

few issues : data folder is C:\input-data, maybe we need some different

**Comment by PeterPetrik** [comment]
@saberraz one without simulated GPS https://www.dropbox.com/s/h1hfxxmg1pfxzg1/inputapp-win-x86_64-2.exe?dl=0

**Comment by saberraz** [comment]
> @saberraz one without simulated GPS https://www.dropbox.com/s/h1hfxxmg1pfxzg1/inputapp-win-x86_64-2.exe?dl=0

This one does not launch.

**Pull request merged**
