### PR TITLE
use project extent instead of WMS extent [1046]

### PR DESCRIPTION
**Pull request by NEDJIMAbelgacem**
This PR addresses this issue:
https://github.com/lutraconsulting/input/issues/1046
I'm not sure if it's very correct to use project extent instead of WMS extent all the time and I'm just assuming it will just work...

### CODE REVIEW

**Comment by saberraz** [comment]
The project extent should work (at least for the time being) both with the new extent the WMS extent. Eventually, we can remove the WMS extent.

**Comment by wonder-sk** [comment]
The logic should be:
1. if project extent is set - use that.
2. else if WMS extent is set - use that (for backward compatibility)
3. else use full extent calculated from map layers.

It looks like you have removed the options 2+3 :-)

**Review by tomasMizera — APPROVED** [review]
looking good!

**Comment by jozef-budac** [comment]
In the latest APK, WMS extent is not used as project extent and after hitting `Zoom to project` in input, maximum extent is used.

**Comment by NEDJIMAbelgacem** [comment]
> In the latest APK, WMS extent is not used as project extent and after hitting `Zoom to project` in input, maximum extent is used.
> 
> Steps to reproduce:
> 
> 1. download tc03_map_canvas project
> 2. in INPUT press Zoom to project. It should show Bratislava. This is OK
> 3. In QGIS, remove project extent and synchronize
> 4. in INPUT hit Zoom to project. Not whole map is present, even when WMS extent is set to Prague city

Should be fixed now, I was using the wrong functions :'/

**Comment by tomasMizera** [comment]
Let's wait for @jozef-budac to test out his project once again and if that is fine, let's merge this one :)

**Comment by jozef-budac** [comment]
Latest update looks ok!

**Pull request merged**
