### PR TITLE
Update input_zh_CN.ts

### PR DESCRIPTION
**Pull request by dfwsbylwy**
fixed Chinese translation

### CODE REVIEW

**Comment by PeterPetrik** [comment]
hi @dfwsbylwy, if you want to change translation, please join Input App team on https://www.transifex.com and fix the translations there. Once the translation is 100% done, transifex will do the pull request automatically.
Thanks!

**Comment by dfwsbylwy** [comment]
OK, Thank you. However, there is still a problem. @PeterPetrik 
My ID is dfwsbylwy in https://www.transifex.com, its authority is **Translator**, and cannot be edit some wrong translation. Please increase the permissions of my ID to **Reviewers**. Then I can correct a few wrong translations, which were my previous translation errors. Please forgive my bad English.

**Comment by saberraz** [comment]
Could you try again?

**Comment by saberraz** [comment]
Your English is great by the way.

**Pull request closed without merging**
