### PR TITLE
Fix of writing/reading QSettings

### PR DESCRIPTION
**Pull request by sklencar**
closes issue related to not be able to save gspTolerance

### CODE REVIEW

**Comment by wonder-sk** [comment]
What was the actual issue, why do we need to set NativeFormat? (and which one is the default normally?)

**Comment by sklencar** [comment]
Actually it is super weird, because the default defaultFormat was NativeFormat. Also checked QSettings::scope as well as appname and organization. All seems to be set ok.
Also checked (just briefly) constructors of QSettings and QSettingsPrivate and it uses `static QSettings::Format globalDefaultFormat = QSettings::NativeFormat;`

If needed, I am happy to investigate it more what actually happen when DefaultFormat is set manually and what is difference from an empty constructor. It is not clear to me and of course it raises suspicious what is actually going on.

**Comment by wonder-sk** [comment]
Yes please if you could have a look... it could be that when we initialize QGIS libs they do some magic with QSettings and override the default? (QGIS likes to use .ini format for settings)

**Comment by sklencar** [comment]
Indeed, the problem was elsewhere - caused by messed up qgis init and initialization of AppSettings.
(https://github.com/lutraconsulting/input/pull/1119/files#diff-c1b709b8a90bef4573ddad8a9b2fbc5d5dbc85e4dc759f95b6d9905931fec24fR346)

**Comment by wonder-sk** [comment]
Cool thanks. Can you maybe add a comment to `AppSettings as;` that says it should be created after qgis libs are initialized, so that next time we do not move it by mistake?

**Review by tomasMizera — APPROVED** [review]
Good catch!
I do not know whether I understood the problem completely. If it was only about `AppSettings` not storing and reloading saved options, then this is working ✔️ . If anything else needs to be retested, let me know.
 
Maybe it would be a good idea to add manual test for QSettings - if they are actually being saved and reloaded. We can mess up things like this from time to time

**Review by wonder-sk — APPROVED** [review]

**Pull request merged**
